# Generated by Django 3.2 on 2021-05-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32)),
                ('fecha', models.DateField()),
                ('registro', models.DateTimeField()),
            ],
        ),
    ]
