# Generated by Django 3.2.2 on 2021-05-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratorio',
            name='registro',
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
