# Generated by Django 3.2.2 on 2021-05-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorios', '0002_auto_20210527_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_entrada', models.DateField()),
                ('Fecha_salida', models.DateField()),
                ('registro', models.DateTimeField()),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('num_control', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('Fecha_entrada', models.DateField()),
                ('Fecha_salida', models.DateField(blank=True, null=True)),
                ('registro', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='registro',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
